// 프로젝트에 필요한 기능과 라이브러리 설정
plugins {
    id 'java' // 자바 프로젝트로 사용
    id 'org.springframework.boot' version '3.3.5' // 스프링부트 기능 사용
    id 'io.spring.dependency-management' version '1.1.6' // 라이브러리 버전을 스프링이 자동 관리
}

group = 'com.example' // 프로젝트 패키지 기본 경로
version = '0.0.1-SNAPSHOT' // 프로젝트 버전 (SNAPSHOT : 개발 중 버전)

java { // Java 버전 설정
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // (21버전 사용)
    }
}

repositories { // 라이브러리 다운로드 저장소
    mavenCentral()
}

dependencies { // 프로젝트에 필요한 기능 추가하는 부분
    implementation 'org.springframework.boot:spring-boot-starter-web' // Controller를 만들고 HTTP 요청을 받게 함
    implementation 'org.springframework.boot:spring-boot-starter-jdbc' // Repository에서 JdbcTemplate으로 SQL 실행 가능하게 함
    implementation 'org.springframework.boot:spring-boot-starter-aop' // Service 실행 전후 공통 로그를 적용할 수 있게 함
    runtimeOnly 'com.mysql:mysql-connector-j' // Spring boot가 mysql 접속할 수 있게 함
    testImplementation 'org.springframework.boot:spring-boot-starter-test' // 테스트 코드 작성에 필요한 기본 기능 제공
}

tasks.named('test') { // 테스트 코드용 라이브러리
    useJUnitPlatform()
}