CREATE DATABASE security;

USE security;

CREATE TABLE persistent_logins (
    username VARCHAR(64) NOT NULL COMMENT '아이디',
    token VARCHAR(64) NOT NULL COMMENT '토큰 값',
    series VARCHAR(64) NOT NULL COMMENT '식별자',
    last_used TIMESTAMP NOT NULL COMMENT '마지막 사용 시간'
);

CREATE TABLE user (
    no BIGINT NOT NULL COMMENT 'PK',
    id VARCHAR(64) NOT NULL COMMENT 'UK',
    username VARCHAR(100) NOT NULL COMMENT '아이디',
    password VARCHAR(200) NOT NULL COMMENT '비밀번호',
    name VARCHAR(100) NOT NULL COMMENT '이름',
    email VARCHAR(200) NULL DEFAULT NULL COMMENT '이메일',
    enabled INT NULL DEFAULT 1 COMMENT '활성화여부', -- 1:true, 0:false
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시'
);

CREATE TABLE board (
    no BIGINT NOT NULL COMMENT 'PK',
    id VARCHAR(64) NULL COMMENT 'UK',
    title VARCHAR(100) NOT NULL COMMENT '제목',
    user_no BIGINT NOT NULL COMMENT 'FK',
    content TEXT NULL COMMENT '내용',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시'
);

CREATE TABLE user_auth (
    no BIGINT NOT NULL COMMENT 'PK',
    id VARCHAR(64) NOT NULL COMMENT 'UK',
    username VARCHAR(100) NOT NULL COMMENT '아이디',
    auth VARCHAR(100) NOT NULL COMMENT '권한',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시'
);

ALTER TABLE user ADD CONSTRAINT PK_USER PRIMARY KEY (no);

ALTER TABLE board ADD CONSTRAINT PK_BOARD PRIMARY KEY (no);

ALTER TABLE user_auth ADD CONSTRAINT PK_USER_AUTH PRIMARY KEY (no);